### ISSUE TITLE
Can't this be part of the cli pwa plugin?

### ISSUE THREAD

**Issue by kommander** [diachedelic/vue-cli-plugin-bundle-service-worker#2]
Hi, I was already wondering why the pwa plugin does not take care of this already. Isn't this a common use case for a lot of users? Maybe this can be part of the pwa plugin. I definitely want my worker to be pre-built as soon as its more than some common caching and needs external libs.

**Comment by diachedelic** [comment]
I agree, however this plugin is still very immature.  For instance there's no way yet to actually configure the build at all.  I'm not part of the vue-cli team, so opening an issue in [their repo](https://github.com/vuejs/vue-cli/) that might be the best way to get an answer.

**Comment by diachedelic** [comment]
However, an advantage of integrating this into the pwa plugin would be that we could take advantage of webpack's [multi-compilers](https://github.com/webpack/webpack/tree/master/examples/multi-compiler)

**Comment by kommander** [comment]
We took another approach by using `InjectManifest` from the `workbox-webpack-plugin` directly. This also works fine with vue-cli serve in dev, when building the SW without caching. With the webpack configuration through `vue.config.js` we use the `webpack.DefinePlugin` and just deactivate the caching in development. There is currently no HMR for the worker, but it can be activated just fine after a rebuild. 

When a build for the worker fails though, currently the complete build fails and will not rebuild in watch mode though. After fixing this, I think this works just fine.

Here's the diff: https://github.com/diachedelic/vue-cli-plugin-bundle-service-worker/compare/master...kommander:webpack-config

**Comment by kommander** [comment]
As we don't want workbox in our SW at all, I reduced the vue-cli-pwa plugin to HTML asset injection and manifest generation only. Additional resources could be injected this way as well and workbox users can inject their workbox script if need be. If anybody finds this to be useful for their project, I'll try to find the time to mold that into a standalone cli plugin, as we currently have the reduced pwa plugin within our codebase.

**Comment by diachedelic** [comment]
@kommander very cool.  However I don't understand why you're using `InjectManifest` when you aren't actually using workbox - are you using another library to cache files listed in the manifest, or have you written the logic yourself?

**Comment by diachedelic** [comment]
So you needed a strategy that was kind of like "cache first until it expires, then network first"?  Have you opened an issue on the workbox page for this?  @jeffposnick is very accomodating.

**Comment by kommander** [comment]
I am Sure he is, I could have written a Plugin and worked around the POST to GET cache issue. Workbox is a great place to get started. I took it as a learning expierience to get known to web workers and did some exploration into indexeddb as well, was fun. Now I Knie where workbox is coming from, also saw there was a discussion around integrating graphql deeper into a caching strategy, very interesting, I want to follow up on that discussion as well.

**Comment by diachedelic** [comment]
I'm not really invested in this plugin anymore, so I'm not going to try get it into core.
