### ISSUE TITLE
Question; How to use this?

### ISSUE THREAD

**Issue by Sjoerd82** [diachedelic/vue-cli-plugin-bundle-service-worker#7]
This is a question more than it is an issue.

I have build a PWA using Vue 2.6 (webpack). I have a Service Worker, and like to move in some code from the Vue app into that Service Worker, so I can streamline some processes which would otherwise be duplicated and not nicely orchestrated in case of multiple open tabs.

Anyway, apparently it's nigh-impossible to import/reuse js-modules in service-workers, for reasons that I don't comprehend. Do I understand correctly that this package takes care of that somehow?

If so, could you perhaps add an example for those that are not very comfortable with Webpack compiling, etc. I'd simply like to import Dexie and one of my own modules into the service-worker.js....

Also, this is a production app, how safe/stable is this package??

**Comment by diachedelic** [comment]
That is exactly what this plugin is for, however I am not currently using Service Workers in my Vue projects, so I can't vouch for its long term maintenance.

Basically you need to already be using the `@vue/pwa` plugin, this plugin just augments that one. If you follow the instructions in the readme correctly, you should be able to import NPM dependencies within your service worker. I am sorry but I do not have time to write an example project right now.

If you want to know how it works, just look at the source code. There isn't much of it!
